### ISSUE TITLE
1.13 something wrong

### ISSUE THREAD

**Issue by 171753355** [Caeden117/CountersPlus#71] opened 2020-11-17 16:53 UTC
The right window only displays the total score, not the percentage and grade, 95% and SS are not displayed

**Comment by PaperT1D** [comment] 2020-11-17 19:45
https://github.com/Caeden117/CountersPlus/issues/70#issuecomment-728629354

**Comment by Caeden117** [comment] 2020-11-17 19:54
This is a duplicate of #70 

To enable the Percentage and Letter Rank, turn on `Advanced HUD` found in the base game Player Settings.

**Closed by Caeden117** 2020-11-17 19:54 UTC
